name: Terraform AWS EC2 Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: terraform  # ✅ Ensure correct repo path

      - name: Verify Directory Structure
        run: |
          pwd
          ls -la
          ls -la terraform || echo "Terraform folder missing!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Initialize Terraform
        run: |
          cd terraform/s3
          terraform init
          terraform validate  # Validate Terraform files

      - name: Terraform Plan
        run: |
          cd terraform/s3
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd terraform/s3
          terraform apply -auto-approve tfplan
